name: Audit Unused Files

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  audit:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
    steps:
      - name: Checkout (current branch)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # default token has push permission unless branch protection blocks it
          persist-credentials: true

      - name: Ensure /summaries exists
        run: |
          set -euo pipefail
          mkdir -p summaries/archive
          # keep directory tracked even if empty
          touch summaries/.gitkeep
          touch summaries/archive/.gitkeep

      - name: Find /scripts files not referenced by workflows
        run: |
          set -euo pipefail

          python - <<'PY'
          import pathlib, re, csv

          ROOT = pathlib.Path(".")
          SCRIPTS_DIR = ROOT / "scripts"
          WF_DIR = ROOT / ".github" / "workflows"
          OUT_DIR = ROOT / "summaries" / "archive"
          OUT_DIR.mkdir(parents=True, exist_ok=True)
          OUT_TXT = OUT_DIR / "unused_scripts_in_workflows.txt"
          OUT_CSV = OUT_DIR / "unused_scripts_in_workflows.csv"

          # Collect workflow file contents (yml/yaml)
          workflow_texts = []
          if WF_DIR.exists():
              for wf in list(WF_DIR.glob("*.yml")) + list(WF_DIR.glob("*.yaml")):
                  try:
                      workflow_texts.append(wf.read_text(errors="ignore"))
                  except Exception:
                      pass
          joined = "\n".join(workflow_texts)

          # Modules referenced via: python -m scripts.foo.bar  -> scripts/foo/bar.py
          mod_paths = set()
          for m in re.finditer(r"(?:^|\s)-m\s+([A-Za-z0-9_\.]+)", joined):
              mod = m.group(1).strip()
              if mod == "scripts" or mod.startswith("scripts."):
                  mod_paths.add((mod.replace(".", "/") + ".py").replace("//", "/"))

          # Gather candidate scripts under /scripts (recursive)
          exts = {".py", ".sh", ".bash", ".zsh", ".ps1"}
          scripts = []
          if SCRIPTS_DIR.exists():
              for p in SCRIPTS_DIR.rglob("*"):
                  if p.is_file() and (p.suffix in exts or (p.stat().st_mode & 0o111)):
                      scripts.append(p)

          direct_refs_text = joined
          unused = []
          rows = [("path","referenced_in_workflows")]

          for p in sorted(scripts):
              rel_from_root = p.as_posix()

              # direct path mention like "scripts/foo.py" or "bash scripts/bar.sh"
              direct_hit = (rel_from_root in direct_refs_text)

              # module mapping for .py
              mod_hit = False
              if p.suffix == ".py":
                  if rel_from_root in mod_paths:
                      mod_hit = True

              used = direct_hit or mod_hit
              rows.append((rel_from_root, "YES" if used else "NO"))
              if not used:
                  unused.append(rel_from_root)

          with OUT_TXT.open("w") as f:
              for u in unused:
                  f.write(u + "\n")

          with OUT_CSV.open("w", newline="") as f:
              csv.writer(f).writerows(rows)
          PY

      - name: Upload results (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unused-scripts-report
          path: |
            summaries/archive/unused_scripts_in_workflows.txt
            summaries/archive/unused_scripts_in_workflows.csv

      - name: Commit summaries to repo
        if: always()
        run: |
          set -euo pipefail

          # Determine current branch name (works for manual runs on protected branches too)
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}}"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Make sure we’re on that branch and up to date
          git checkout "$BRANCH"
          git pull --ff-only origin "$BRANCH" || true

          # Ensure the directory is tracked
          touch summaries/.gitkeep summaries/archive/.gitkeep

          # Stage only the summaries output
          git add summaries/.gitkeep summaries/archive/.gitkeep \
                  summaries/archive/unused_scripts_in_workflows.txt \
                  summaries/archive/unused_scripts_in_workflows.csv

          # Commit if there are changes; otherwise do nothing
          git diff --cached --quiet || git commit -m "chore: update unused scripts report"

          # Push (will no-op if nothing to push; will warn if protections block)
          git push origin "$BRANCH" || echo "::warning::Push blocked by branch protections; artifacts still uploaded."

      - name: Job Summary
        if: always()
        run: |
          echo "## Scripts in /scripts not referenced by any workflow" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -s summaries/archive/unused_scripts_in_workflows.txt ]; then
            COUNT=$(wc -l < summaries/archive/unused_scripts_in_workflows.txt | tr -d ' ')
            echo "**Count:** $COUNT" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            while read -r line; do
              echo "- \`$line\`" >> $GITHUB_STEP_SUMMARY
            done < summaries/archive/unused_scripts_in_workflows.txt
          else
            echo "No unused scripts found." >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**CSV:** \`summaries/archive/unused_scripts_in_workflows.csv\`" >> $GITHUB_STEP_SUMMARY
