name: Build Insights Metrics (Manual)

on:
  workflow_dispatch:
    inputs:
      season:
        description: "Season (e.g., 2025). Leave blank to auto-detect latest."
        required: false
        type: string

permissions:
  contents: write

jobs:
  build-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run aggregator
        env:
          SEASON: ${{ inputs.season }}
        run: |
          python -m pip install --upgrade pip
          # no external deps needed
          python scripts/aggregate_metrics.py

      - name: Commit metrics
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add docs/data/metrics/*.csv
          if git diff --cached --quiet; then
            echo "No metrics changes."
          else:
            git commit -m "Build metrics for season ${{ inputs.season }}"
            git push
          fi
