name: Build Metrics (Manual)

on:
  workflow_dispatch:
    inputs:
      season:
        description: "Season year (e.g., 2025). Leave blank to auto-detect in the script."
        required: false
        default: ""

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Pre-run snapshot
        shell: bash
        run: |
          set -Eeuo pipefail
          echo "=== Existing finals (newest first) ==="
          if [ -d docs/data/final ]; then
            ls -lt docs/data/final || true
          else
            echo "docs/data/final does not exist"
          fi
          echo "=== Existing metrics BEFORE ==="
          if [ -d docs/data/metrics ]; then
            ls -l docs/data/metrics || true
            if compgen -G "docs/data/metrics/*.csv" > /dev/null; then
              echo "=== Hashes BEFORE ==="
              sha256sum docs/data/metrics/*.csv | sort
            fi
          else
            echo "docs/data/metrics does not exist (yet)"
          fi

      - name: Install deps
        shell: bash
        run: |
          set -Eeuo pipefail
          python -m pip install --upgrade pip
          python -m pip install pandas

      - name: Run aggregator
        shell: bash
        env:
          SEASON: ${{ inputs.season }}
        run: |
          set -Eeuo pipefail
          if [ -n "${SEASON:-}" ]; then
            echo "Season provided to script via SEASON env: ${SEASON}"
          else
            echo "No season provided; script will auto-detect."
          fi
          echo "=== Running: scripts/aggregate_metrics.py ==="
          python scripts/aggregate_metrics.py ${SEASON:+$SEASON}

      - name: Post-run snapshot
        if: always()
        shell: bash
        run: |
          set -Eeuo pipefail
          echo "=== Metrics AFTER ==="
          if [ -d docs/data/metrics ]; then
            ls -l docs/data/metrics || true
            if compgen -G "docs/data/metrics/*.csv" > /dev/null; then
              echo "=== Hashes AFTER ==="
              sha256sum docs/data/metrics/*.csv | sort
            fi
          else
            echo "docs/data/metrics directory missing after run"
          fi

      - name: Commit metrics
        if: always()
        shell: bash
        run: |
          set -Eeuo pipefail
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"

          # Preview changes
          echo "=== Diff (name-only) ==="
          git add -N docs/data/metrics/*.csv 2>/dev/null || true
          git diff --name-only -- docs/data/metrics || true
          echo "=== Diffstat ==="
          git diff --stat -- docs/data/metrics || true

          # Commit if there are staged changes
          git add docs/data/metrics/*.csv 2>/dev/null || true
          git commit -m "Metrics updated" && git push || echo "No metric changes"
