name: Ingest picks from Issues

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write

jobs:
  ingest:
    if: ${{ github.event_name == 'issues' && startsWith(github.event.issue.title, 'PICKS ') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   # REQUIRED

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run ingest script
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY:  ${{ github.event.issue.body }}
        run: |
          python scripts/ingest_issue.py

      - name: Commit picks file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add picks/*.json
          git commit -m "Add picks from issue: ${{ github.event.issue.number }}" || echo "No changes"
          git push

      - name: Comment and close
        uses: actions-ecosystem/action-add-comment@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          body: "Picks saved. Closing."
      - uses: actions-ecosystem/action-close-issue@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
