name: SMOKE
on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   # <— this pulls your repo into the runner

      - run: echo "✅ Actions can run and see the repo"

      - name: Make a test commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          mkdir -p data && date -u > data/smoke.txt
          git add data/smoke.txt
          git commit -m "smoke" || echo "no changes"
          git push
